application/src/Entity/User.php
<?php


namespace App\Entity;

use App\Entity\UserProjectStatus;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="app_user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email", message="user_unique_email")
 * @UniqueEntity("username", message="user_unique_username")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publicMail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserProjectStatus", mappedBy="user")
     */
    private $projectStatus;

    /**
     * @ORM\Column(type="json_array")
     */
    private $roles;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $anonymous;

    /**
     * Random string sent to the user email address in order to verify it.
     *
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $confirmationToken;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $passwordRequestedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TranscriptionLog", mappedBy="user")
     */
    private $transcriptionLogs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ReviewRequest", mappedBy="user", orphanRemoval=true)
     */
    private $reviewRequests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="user", orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean")
     */
    private $firstTranscript;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Transcription", mappedBy="subscribersUsers")
     */
    private $subscribedTranscriptions;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastAccess = null;


    public function __construct()
    {
        $this->active = false;
        $this->publicMail = true;
        $this->firstTranscript = true;
        $this->anonymous = false;
        $this->projectStatus = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->transcriptionLogs = new ArrayCollection();
        $this->reviewRequests = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->subscribedTranscriptions = new ArrayCollection();
    }

    public function getId() :int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): string
    {
        return $this->lastname . ' ' . $this->firstname;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublicMail(): ?bool
    {
        return $this->publicMail;
    }

    public function setPublicMail(bool $publicMail): self
    {
        $this->publicMail = $publicMail;

        return $this;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles($roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function isAnonymous(): ?bool
    {
        return $this->anonymous;
    }

    public function setAnonymous(bool $anonymous): self
    {
        $this->anonymous = $anonymous;
        $this->eraseCredentials();

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): self
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }

    public function getPasswordRequestedAt(): ?\DateTimeInterface
    {
        return $this->passwordRequestedAt;
    }

    public function setPasswordRequestedAt(\DateTimeInterface $passwordRequestedAt = null): self
    {
        $this->passwordRequestedAt = $passwordRequestedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
          $this->id,
          $this->firstname,
          $this->lastname,
          $this->username,
          $this->password,
          $this->email,
          $this->publicMail,
          $this->active,
          $this->anonymous,
          $this->createdAt,
          $this->updatedAt,
      ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list(
          $this->id,
          $this->firstname,
          $this->lastname,
          $this->username,
          $this->password,
          $this->email,
          $this->publicMail,
          $this->active,
          $this->anonymous,
          $this->createdAt,
          $this->updatedAt,
      ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function isEnabled()
    {
        return $this->active;
    }


    // only to satisfy interface
    public function getSalt()
    {
        return null;
    }

    // only to satisfy interface
    public function eraseCredentials()
    {
        $this->roles = [];
    }

    /**
     * @return Collection|UserProjectStatus[]
     */
    public function getProjectStatus(): Collection
    {
        return $this->projectStatus;
    }

    public function addProjectStatus(UserProjectStatus $projectStatus): self
    {
        if (!$this->projectStatus->contains($projectStatus)) {
            $this->projectStatus[] = $projectStatus;
            $projectStatus->setUser($this);
        }

        return $this;
    }

    public function removeProjectStatus(UserProjectStatus $projectStatus): self
    {
        if ($this->projectStatus->contains($projectStatus)) {
            $this->projectStatus->removeElement($projectStatus);
            // set the owning side to null (unless already changed)
            if ($projectStatus->getUser() === $this) {
                $projectStatus->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TranscriptionLog[]
     */
    public function getTranscriptionLogs(): Collection
    {
        return $this->transcriptionLogs;
    }

application/templates/project/display-logs.html.twig
{% extends "base.html.twig" %}

{% block body %}
  {% include 'project/navigation.html.twig' with {'current': 'project_edit'} %}
  <div id="main-container">
    <h1 class="page-title">{{"events"|trans}}</h1>
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            {% include 'log/listing.html.twig' with {'global': false, 'personal': false} %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

application/templates/project/display.html.twig
{% extends "base.html.twig" %}

{% import "user/macros.html.twig" as macros %}
{% import "project/macros.html.twig" as pmacros %}

{% block body %}
  {% set userStatus = app.user|status(project) %}

  {% include 'project/navigation.html.twig' with {'current': ''} %}
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active {{ project.image ? "carousel-custom" }}" style="{{ project.image ? 'background-image: url(' ~ asset('project_files/'~project.id~'/'~project.image) ~ ')' }}">
      </div>
    </div>
  </div>
  <div id="catchphrase-container">
    <span id="catchphrase">{{ project.catchPhrase }}</span>
  </div>
  <div id="main-container">
    <div class="row">
      <div class="col-12 col-sm-6 col-md-8 col-lg-8 col-xl-8">
        <div class="card">
          <div class="card-body">
            {% if not project.archived %}
            <div class="alert alert-info" role="alert">
              {% if not app.user %}
              {{ "login_or_register_link"|trans({'%login%': path('user_login'), '%register%':path('user_login')  }) | raw }}
              {% else %}
              {% if not userStatus %}
              {{ "project_register_link"| trans({'%register%': path('status_request', {id: project.id}) }) | raw }}
              {% else %}
              {% if not userStatus.enabled %}
              {{"registration_waiting_for_validation"|trans}}
              {% else %}
              {{"transcribe_link"| trans({'%transcribe%': path('project_transcriptions', {id: project.id})}) | raw }}
              {% endif %}
              {% endif %}
              {% endif %}
            </div>
            {% endif %}
            {{ project.description | raw }}
          </div>
        </div>

      {% if comments and (not project.archived and app.user and userStatus and userStatus.enabled) %}
      <div class="card mt-2">
        <div class="card-header">
          {{"comments"|trans}}
        </div>
          <ul class="list-group list-group-flush">
          {% for comment in comments %}
          <li class="list-group-item">
            {{ comment.content }}
            <span class="float-right">
              <small>
                <a target="_blank" href="{{ path('media_transcription_display', {'id': comment.transcription.media.id}) }}">
                  {{comment.transcription.media.name}}
                </a>
                -
                {{ comment.createdAt|date("d/m/Y H:i") }}
                -
                <a target="_blank" href="{{ path('user_profile', {'id': comment.user.id}) }}">
                  {{ comment.user.username }}
                </a>
              </small>
            </span>
          </li>
          {% endfor %}
          </ul>
      </div>
      {% endif %}
      </div>

      <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">

          <div class="card">
            <div class="card-header">
              <i class="fas fa-chart-bar"></i> {{'project_data'|trans}}
            </div>
            <ul class="list-group list-group-flush">
               <li class="list-group-item">
                 {{ project.public ? 'is_public'|trans : 'project_is_not_public'|trans}}
               </li>
               <li class="list-group-item">
                 {{"project_media_count"|trans({'%count%': project.medias|length})}}
               </li>
               <li class="list-group-item">
                 {% set percents = project|percents %}
                 {{ pmacros.displayPercents(percents) }}
              </li>
            </ul>
          </div>

          {% if userStatus and project | isAuthorizedOnProject('validateTranscription') %}
          <div class="card mt-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-justify">
                {% if userStatus.subscribe == true %}
                  {{"subscribed"|trans|raw}} <a href='{{ path('status_subscribe_toggle', {'id': project.id}) }}'>{{"unsubscribe"|trans}}</a>
                {% else %}
                  {{"unsubscribed"|trans|raw}} <a href='{{ path('status_subscribe_toggle', {'id': project.id}) }}'>{{"subscribe"|trans}}</a>
                {% endif %}
              </li>
              {% if project | isAuthorizedOnProject('manageUser') %}
              <li class="list-group-item text-justify">
                {% if userStatus.subscribeRegistration == true %}
                  {{"subscribed_registration"|trans|raw}} <a href='{{ path('status_subscribe_registration_toggle', {'id': project.id}) }}'>{{"unsubscribe"|trans}}</a>
                {% else %}
                  {{"unsubscribed_registration"|trans|raw}} <a href='{{ path('status_subscribe_registration_toggle', {'id': project.id}) }}'>{{"subscribe"|trans}}</a>
                {% endif %}
              </li>
              {% endif %}
            </ul>
          </div>
          {% endif %}

        <div class="mt-3">
          {% include('transcribe/contributors.html.twig') %}
        </div>

      </div>
    </div>
  </div>

{% endblock %}

application/templates/project/edit-advanced.html.twig
{% extends "base.html.twig" %}

{% import _self as formMacros %}

{% block stylesheets %}
{{parent()}}
<link rel="stylesheet" href="{{ asset('build/css/create-project.css') }}">
{% endblock %}

{% block body %}

{% include 'project/navigation.html.twig' with {'current': 'project_edit'} %}

<div id="main-container">

  <h1 class="page-title">
    {{'edit_advanced'|trans}}
  </h1>

  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
            {{ form_start(form) }}
            {{ form_row(form.css) }}
            {{ form_row(form.tesseractLanguage) }}
              <div class="row mt-3 mb-4">
                <div class="col">
                  {{ form_row(form.xslt_export) }}
                  {% if project|hasXsl %}
                  <div class="project-xsl-row">
                      <a download href="{{ asset('project_files/'~ project.id ~ '/export.xsl') }}">export.xsl</a>
                      <button data-project-id="{{ project.id }}" id="delete-xsl" type="button" role="button" class="btn btn-sm btn-danger">
                        <i class="fas fa-trash"></i>
                      </button>
                  </div>
                  {% endif %}
                  <span class="text-muted small">Vous trouverez <a download href="{{ asset("data/xsl-exemple.xsl") }}">ici</a> un exemple de xsl</span>
                </div>
                <div class="col">
                  {{ form_label(form.json_schema) }}
                  {{ form_errors(form.json_schema) }}

                  {{ form_widget(form.json_schema) }}
                  <div class="text-right">
                    <span class="text-muted small">{{"json_generator_help"|trans|raw}} - {{"tei2json_help"|trans|raw}}</span>
                  </div>

                  {% if project|hasScheme %}
                  <div class="project-json-row">
                      <a download href="{{ asset('project_files/'~ project.id ~ '/tei-schema.json') }}">tei-schema.json</a>
                      <button data-project-id="{{ project.id }}" id="delete-json" type="button" role="button" class="btn btn-sm btn-danger">
                        <i class="fas fa-trash"></i>
                      </button>
                  </div>
                  {% endif %}
                </div>

              </div>

              {{ form_widget(form._token) }}
              {{ form_row(form.save) }}
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}


{% block javascripts %}
  {{ parent() }}
  <script src="{{ asset('build/js/edit-advanced-project.js') }}"></script>
{% endblock %}

application/templates/project/edit-basic.html.twig
{% extends "base.html.twig" %}

{% import _self as formMacros %}

{% block stylesheets %}
{{parent()}}
<link rel="stylesheet" href="{{ asset('build/css/create-project.css') }}">
{% endblock %}

{% block body %}

{% if project.id %}
  {% include 'project/navigation.html.twig' with {'current': 'project_edit'} %}
{% endif %}

<div id="main-container">
  <h1 class="page-title">
  {% if not project.id %}
    {{'project_create'|trans}}</h1>
  {% else %}
    {{'edit_basic'|trans}}
  {% endif %}
  </h1>
  
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          {{ form_start(form) }}
            {{ form_row(form.name) }}
            {{ form_row(form.description) }}
            {{ form_row(form.public) }}
            {{ form_row(form.catchPhrase) }}
            {% if project.id is null %}
              {{ form_row(form.manager) }}
            {% endif %}
            {{ form_row(form.projectHelpLink) }}
            {% if project.projectHelpLink %}
            <div class="row project-helplink-row text-right">
              <div class="col">
                <a download class="project-helplink" href="{{ asset('project_files/'~ project.id ~ '/' ~ project.projectHelpLink) }}">{{ project.projectHelpLink }}</a>
                <button data-project-id="{{ project.id }}" id="delete-helplink"k type="button" role="button" class="btn btn-sm btn-danger">
                  <i class="fas fa-trash"></i>
                </button>
              </div>
            </div>
            {% endif %}

            {{ form_row(form.nbValidation) }}
            {{ form_row(form.image) }}
            {% if project.image %}
            <div class="row project-image-row text-right">
              <div class="col">
                <img width="200px" class="project-image-md" src="{{ asset('project_files/'~ project.id ~ '/' ~ project.image) }}">
                <input type="hidden" name="previous_image" value="{{ project.image }}" />
                <button data-project-id="{{ project.id }}" id="delete-image" type="button" role="button" class="btn btn-sm btn-danger">
                  <i class="fas fa-trash"></i>
                </button>
              </div>
            </div>
            {% endif %}

            {{ form_widget(form._token) }}
            {{ form_row(form.save) }}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block javascripts %}
  {{ parent() }}
  <script src="{{ asset('build/js/edit-basic-project.js') }}"></script>
{% endblock %}

application/templates/project/edit-iiif.html.twig
{% extends "base.html.twig" %}
{% import "project/macros.html.twig" as macros %}

{% block body %}
{% include 'project/navigation.html.twig' with {'current': 'project_edit'} %}

<div id="main-container">
  <h1 class="page-title">{{"edit_iiif"|trans}}</h1>

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">

        <a class="mb-2 btn btn-sm btn-primary" href="{{path("iiif_edit", { projectId: project.id})}}">
          <i class="fas fa-plus"></i> {{"add_iiif_server"|trans}}
        </a>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">{{"iiif_server_name"|trans}}</th>
              <th scope="col">{{"iiif_server_url"|trans}}</th>
              <th scope="col">{{"iiif_server_mediacount"|trans}}</th>
              <th scope="col">{{"iiif_server_actions"|trans}}</th>
            </tr>
          </thead>
          {% for server in project.iiifServers %}
          <tr>
            <td>{{server.name}}</td>
            <td>{{server.url}}</td>
            <td>{{server.medias|length}}</td>
            <td>
              <a class="btn btn-sm btn-secondary" href="{{path("iiif_edit", { projectId: project.id, serverId: server.id})}}">
                <i class="fas fa-edit"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/project/export.html.twig
{% extends "base.html.twig" %}

{% block body %}
  {% include 'project/navigation.html.twig' with {'current': 'project_edit'} %}
  <div id="main-container">
    <h1 class="page-title">{{"export"|trans}}</h1>
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
          <div class="card-body">
            <h5>{{"export_form_title"|trans}}</h5>
              {{ form_start(form) }}
              {{ form_row(form.dir) }}
              {{ form_row(form.transcription_status) }}
              {{ form_widget(form._token) }}
              {{ form_row(form.transcriptions) }}
              <div class="ml-4">
                {{ form_row(form.transcriptions_apply_xsl) }}
                {{ form_row(form.transcriptions_metadatas) }}
              </div>
              {{ form_end(form) }}
              {{ form_row(form.save) }}
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script src="{{ asset('build/js/project-export.js') }}"></script>
  <script src="{{ asset('build/js/submit-disable.js') }}"></script>
{% endblock %}

application/templates/project/list.html.twig
{% extends "base.html.twig" %}
{% import "project/macros.html.twig" as macros %}

{% block body %}
  <div class="bluebg" id="main-container">
    <h1 class="page-title">{{'project_list'|trans}}</h1>
    <div class="project-grid">
    {% for project in projectsUnarchived %}
      {{ macros.displayProject(project) }}
    {% endfor %}
    </div>
    {% if projectsArchived|length > 0 %}
      <h1 class="page-title">Projets archivés</h1>
      <div class="project-grid archived">
        {% for project in projectsArchived %}
          {{ macros.displayProject(project) }}
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock %}

application/templates/project/message.html.twig
{% extends "base.html.twig" %}

{% block body %}
  {% include 'project/navigation.html.twig' with {'current': null} %}

  <div id="main-container">

    <h1 class="page-title">Message aux membres du projet</h1>
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
          <div class="card-body">
              {{form(form) }}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

application/templates/project/user-status-form.html.twig
{{ form(form, {'action': path('status_form_post',{"id": status.id})}) }}

application/templates/project/user-statuses.html.twig
{% extends "base.html.twig" %}

{% block body %}
{% include 'project/navigation.html.twig' with {'current': 'project_edit'} %}

<div id="main-container">
  <h1 class="page-title">{{"users"|trans}}</h1>

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">{{ "username"| trans }}</th>
                  <th scope="col">{{ "status"| trans }}</th>
                  <th scope="col">{{ "project_enabled"| trans }}</th>
                  <th scope="col">{{ "actions"| trans }}</th>
                </tr>
              </thead>
              <tbody>
                {% import _self as macros %}
                {# INSCRIPTIONS NON VALIDEES #}
                {% set count = 0 %}
                {% for userStatus in project.userStatuses if not userStatus.enabled %}
                  {% set count = count+1 %}
                  {{macros.userStatusLine(userStatus)}}
                {% endfor %}
                {% if count != 0 %}
                  <tr><td colspan="4"></td><tr/>
                {% endif %}
                {# INSCRIPTIONS VALIDEES #}
                {% for userStatus in project.userStatuses|sort((a, b) => a.status <= b.status) if userStatus.enabled %}
                  {{macros.userStatusLine(userStatus)}}
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div id="status-modal" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">{{ "status_edit" | trans}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div id="status-modal-body" class="modal-body">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script src="{{ asset('build/js/user-status-form.js') }}"></script>
{% endblock %}

{% macro userStatusLine(userStatus) %}
  {% set statusName  = userStatus.status.name %}
  <tr class="{{not userStatus.enabled ? "table-secondary" : statusName == "user_status_manager_name" ? "table-success" : (statusName == "user_status_validator_name") ?  "table-info": "" }}">
    <td>{{ userStatus.user.username }}</td>
    <td>{{ userStatus.status.name | trans }}</td>
    <td>{{ userStatus.enabled ? "yes"|trans : "no"|trans }}</td>
    <td>
      <a href="#" type="button" class="btn btn-link edit-status" data-status-id="{{ userStatus.id}}">
        <i class="fas fa-pencil-alt" aria-hidden="true"></i>
        {{ "status_edit" | trans}}
      </a>
      <a href="{{ path("status_remove", {id: userStatus.id})}}" type="button" class="btn btn-link">
        <i class="fas fa-times" aria-hidden="true"></i>
        {{ "status_remove" | trans}}
      </a>
      <a href="{{ path("status_toggle", {id: userStatus.id})}}" type="button" class="btn btn-link">
        {% if userStatus.enabled %}
        <i class="fa fa-toggle-on" aria-hidden="true"></i> {{ "status_toggle_off" | trans}}
        {% else %}
        <i class="fa fa-toggle-off" aria-hidden="true"></i> {{ "status_toggle_on" | trans}}
        {% endif %}
      </a>
    </td>
  </tr>
{% endmacro %}