application/src/Entity/User.php
<?php


namespace App\Entity;

use App\Entity\UserProjectStatus;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="app_user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email", message="user_unique_email")
 * @UniqueEntity("username", message="user_unique_username")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publicMail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserProjectStatus", mappedBy="user")
     */
    private $projectStatus;

    /**
     * @ORM\Column(type="json_array")
     */
    private $roles;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $anonymous;

    /**
     * Random string sent to the user email address in order to verify it.
     *
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $confirmationToken;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $passwordRequestedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TranscriptionLog", mappedBy="user")
     */
    private $transcriptionLogs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ReviewRequest", mappedBy="user", orphanRemoval=true)
     */
    private $reviewRequests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="user", orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean")
     */
    private $firstTranscript;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Transcription", mappedBy="subscribersUsers")
     */
    private $subscribedTranscriptions;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastAccess = null;


    public function __construct()
    {
        $this->active = false;
        $this->publicMail = true;
        $this->firstTranscript = true;
        $this->anonymous = false;
        $this->projectStatus = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->transcriptionLogs = new ArrayCollection();
        $this->reviewRequests = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->subscribedTranscriptions = new ArrayCollection();
    }

    public function getId() :int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): string
    {
        return $this->lastname . ' ' . $this->firstname;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublicMail(): ?bool
    {
        return $this->publicMail;
    }

    public function setPublicMail(bool $publicMail): self
    {
        $this->publicMail = $publicMail;

        return $this;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles($roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function isAnonymous(): ?bool
    {
        return $this->anonymous;
    }

    public function setAnonymous(bool $anonymous): self
    {
        $this->anonymous = $anonymous;
        $this->eraseCredentials();

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): self
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }

    public function getPasswordRequestedAt(): ?\DateTimeInterface
    {
        return $this->passwordRequestedAt;
    }

    public function setPasswordRequestedAt(\DateTimeInterface $passwordRequestedAt = null): self
    {
        $this->passwordRequestedAt = $passwordRequestedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
          $this->id,
          $this->firstname,
          $this->lastname,
          $this->username,
          $this->password,
          $this->email,
          $this->publicMail,
          $this->active,
          $this->anonymous,
          $this->createdAt,
          $this->updatedAt,
      ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list(
          $this->id,
          $this->firstname,
          $this->lastname,
          $this->username,
          $this->password,
          $this->email,
          $this->publicMail,
          $this->active,
          $this->anonymous,
          $this->createdAt,
          $this->updatedAt,
      ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function isEnabled()
    {
        return $this->active;
    }


    // only to satisfy interface
    public function getSalt()
    {
        return null;
    }

    // only to satisfy interface
    public function eraseCredentials()
    {
        $this->roles = [];
    }

    /**
     * @return Collection|UserProjectStatus[]
     */
    public function getProjectStatus(): Collection
    {
        return $this->projectStatus;
    }

    public function addProjectStatus(UserProjectStatus $projectStatus): self
    {
        if (!$this->projectStatus->contains($projectStatus)) {
            $this->projectStatus[] = $projectStatus;
            $projectStatus->setUser($this);
        }

        return $this;
    }

    public function removeProjectStatus(UserProjectStatus $projectStatus): self
    {
        if ($this->projectStatus->contains($projectStatus)) {
            $this->projectStatus->removeElement($projectStatus);
            // set the owning side to null (unless already changed)
            if ($projectStatus->getUser() === $this) {
                $projectStatus->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TranscriptionLog[]
     */
    public function getTranscriptionLogs(): Collection
    {
        return $this->transcriptionLogs;
    }

application/templates/base-include/flashmessages.html.twig
{% for label, messages in app.flashes %}
  {% for message in messages %}
    <div class="invisible" id="flashes">
      <div class="flash" data-label="{{ label }}" data-message="{{ message|e('html_attr') }}"></div>
    </div>
  {% endfor %}
{% endfor %}

application/templates/base-include/footer.html.twig
<footer id="footer" class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">{{"backtotop"|trans}}</a> <br/>
      <a href="{{ path('terms') }}">{{"terms"|trans}}</a> <br/>
    </p>
    <p>
      <a class="btn" href=" http://univ-grenoble-alpes.fr" target="_blank">
        <img class="logo-bottom" data-toggle="tooltip" title="Université Grenoble Alpes" src="{{ asset('img/logos/logo_univ_grenoble_alpes.jpg') }}"/>
      </a>
      <a class="btn" href="http://www.cnrs.fr" target="_blank">
        <img class="logo-bottom" data-toggle="tooltip" title="CNRS Centre national de la recherche scientifique" src="{{ asset('img/logos/logo_cnrs.jpg') }}"/>
      </a>
      <a class="btn" target="_blank" href="http://litt-arts.univ-grenoble-alpes.fr/litt-arts-arts-et-pratiques-du-texte-de-l-image-de-l-ecran-et-de-la-scene-62796.kjsp">
        <img class="logo-bottom" data-toggle="tooltip" title="Litt&Arts (UMR 5316) - Arts et pratiques du texte, de l'image, de l'écran et de la scène" src="{{ asset('img/logos/logo_littarts.png') }}"/>
      </a>
      <a class="btn" href="https://demarreshs.hypotheses.org/" target="_blank">
        <img class="logo-bottom" data-toggle="tooltip" title="DémarreSHS!" src="{{ asset('img/logos/logo_demarre_shs.jpg') }}"/>
      </a>
      <a class="btn" href="https://www.huma-num.fr/" target="_blank">
        <img class="logo-bottom" data-toggle="tooltip" title="Huma-Num - Hébergeur" src="{{ asset('img/logos/logo_hn.jpg') }}"/>
      </a>
      <a class="btn" href="https://www.elan-numerique.fr/" target="_blank">
        <img class="logo-bottom" data-toggle="tooltip" title="ELAN - Equipe Littérature et Arts Numériques" src="{{ asset('img/logos/logo_elan.png') }}"/>
      </a>
    </p>
  </div>
</footer>

application/templates/base-include/navbar.html.twig
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ path('home') }}">
      {% if platform.logo %}
        <img class="platform-logo" src="{{ asset('platform/'~ platform.logo) }}">
      {% endif %}
      {{ platform.name  }}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <a class="nav-link" href="{{ path('project_list') }}">
            <i class="fas fa-rocket"></i> {{'project_list'|trans}}
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ path('actu') }}">
            <i class="fas fa-bullhorn"></i> {{'actu'|trans}}
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ path('stats') }}">
          <i class="fas fa-chart-bar"></i> {{'stats'|trans}}
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ path('about') }}">
            <i class="fas fa-bookmark"></i> {{'about'|trans}}
          </a>
        </li>

        {% if is_granted('ROLE_ADMIN', app.user) %}

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-cog"></i> Administration
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ path("project_create") }}">
                <i class="fas fa-plus"></i> {{'add_project' | trans}}
              </a>
              <a href="{{ path('admin_user_list') }}" class="dropdown-item">
                <i class="fas fa-users"></i> {{'administrate_users_menu'|trans}}
              </a>
              <a href="{{ path('admin_platform_properties')}}" class="dropdown-item">
                <i class="fas fa-cogs"></i> {{'administrate_platform_menu'|trans}}
              </a>
              <a class="dropdown-item" href="{{ path('admin_edito_list')}}">
                <i class="fas fa-newspaper"></i> {{'administrate_edito_content'|trans}}
              </a>
              <a class="dropdown-item" href="{{ path('admin_log_display')}}">
                <i class="fas fa-clipboard-list"></i> {{'administrate_log_display'|trans}}
              </a>
            </div>
          </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav float-right">
        {% if app.user %}
          {% set countUnread = app.user|countUnread %}
          <li class="nav-item">
            <a class="nav-link" href="{{ path('message_list')}}">
              <i class="fas fa-envelope {{ countUnread > 0 ? "fa-spin"}}"></i> {{ countUnread }}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ path('user_profile', {'id': app.user.id}) }}">
              <i class="fas fa-user fa-fw"></i> {{app.user.fullname}}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ path('logout') }}">
              <i class="fas fa-sign-out-alt fa-fw"></i> {{'logout'|trans}}
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ path('user_login') }}">
              <i class="fas fa-sign-out-alt fa-fw"></i> {{'login'|trans}}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ path('user_register') }}">
              <i class="fas fa-id-card fa-fw"></i> {{'register'|trans}}
            </a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>